kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-storage
  labels:
    type: grafana-data
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: grafanadata
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/grafana/data"
