kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-storage
  labels:
    type: prometheus-data
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: prometheusdata
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/prometheus/data"
