apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-persistent-claim
  namespace: monitoring
spec:
  storageClassName: prometheusdata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
