apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deploy
  namespace: logging
  labels:
    app: es-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-deploy
  template:
    metadata:
      labels:
        app: es-deploy
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.30
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 20
          periodSeconds: 30
        ports:
        - containerPort: 9200
        - containerPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: es6
spec:
  type: NodePort
  selector:
    app: es-deploy
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
    nodePort: 30001
  - name: "9300"
    port: 9300
    targetPort: 9300
    nodePort: 30002
