apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog-deploy
  namespace: logging
  labels:
    app: graylog-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog-deploy
  template:
    metadata:
      labels:
        app: graylog-deploy
    spec:
      containers:
      - name: graylog3
        image: graylog/graylog:3.0
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: g0ABP9MJnWCjWtBX9JHFgjKAmD3wGXP3E0JQNOKlquDHnCn5689QAF8rRL66HacXLPA6fvwMY8BZoVVw0JqHnSAZorDDOdCk
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://192.168.247.130:30003/
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://es6.logging.svc.cluster.local:9200
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongo.logging.svc.cluster.local:27017/graylog
        ports:
        - containerPort: 9000
        - containerPort: 12201
    
---
apiVersion: v1
kind: Service
metadata:
  name: graylog3
spec:
  type: NodePort
  selector:
    app: graylog-deploy
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    nodePort: 30003
  - name: "12201"
    port: 12201
    targetPort: 12201
    nodePort: 30004
