apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-claim
  namespace: logging
spec:
  storageClassName: mongodata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
