kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-storage
  labels:
    type: mongo-data
  namespace: logging
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: mongodata
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/graylog/data"
